**NUMPY EXERCISE**

**1. Import Numpy**

In [0]:
import numpy as np

**2. Manually create a matrix**

Create a 3-by-5 matrix and print it out to the screen

In [0]:
import numpy as np

a = np.array([[1,2,3,4,10],[4,5,6,7,9],[4,6,5,3,4]])
a.shape = (3,5)
print(a)

[[ 1  2  3  4 10]
 [ 4  5  6  7  9]
 [ 4  6  5  3  4]]


**3. Manually create a vector**

Create a vector which has 10 elements and print it out to the screen

In [0]:
import numpy as np
vector = np.arange(1,11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


**4. Automatically create matrix**



1.   Automatically create a 3-by-5 matrix which has interger values in the range of [0, 100]
2.   Automatically create a 5-by-7 matrix which has interger values in the range of [0, 100]
3.   Print out the above 2 matricces to the screen
4.   Implementy matrix multiplication of the above 2 matrices and print the result to the screen (let us call this result matrixx is C)




In [0]:
import numpy as np
a = np.random.randint(0,100,size=(3,5))
b = np.random.randint(0,100,size=(5,7))
print(a)
print(b)

[[41 13 52 92 61]
 [74 32 86  8 25]
 [53 89 32 61 38]]
[[60 99 53 30 76 40 90]
 [ 3 11 79 77 66 38 25]
 [12 16 26 82 20 52 26]
 [63 54 72 75 49 61 92]
 [76 71 39 65 77 16 97]]


**5. Scalar multiplication**

Input a number fromm keyboard and multiply this number with the above matrix C and print the result to the screen

In [0]:
#Your code here

**6. Automatically create vector**

Automattically create a vector at size of 7-by-1 which has values in the range of [-10, 30]. And multiply the C matrix with this vector. Print the result to the screen.

In [0]:
vec = np.random.randint(-10,30,size=(7,1))
vec

array([[  7],
       [ 22],
       [ 18],
       [ 20],
       [  4],
       [-10],
       [-10]])

**7. Matrix slicing**



1.   Automatically create a matrix at size of 7-by-15
2.   Print out the first column of this matrix 
3.   Print out the third row of this matrix
4.   Print out the element at the second column and fourth row



In [0]:
import numpy as np 
e = np.random.randint(0,30,size=(7, 15))
e

array([[27,  0,  8, 10, 29,  5, 23, 16,  1,  6, 21, 11, 14, 29, 24],
       [10, 29,  8, 22, 18, 14, 21,  1, 17, 20,  1,  5, 17, 11, 25],
       [ 5, 26, 14,  4,  3,  7,  7,  0, 12, 20, 24, 28, 10,  3, 10],
       [ 6, 13,  6,  7, 19,  4, 10,  1,  7,  4, 26,  7,  5, 14, 12],
       [ 1, 27,  0, 20, 17,  6, 23,  8, 19, 20,  3,  5, 22, 14, 16],
       [17, 21,  6, 22, 17, 20, 13, 23, 10,  8, 23,  1, 17, 10, 20],
       [ 7, 17,  1, 23, 17,  3, 24, 15,  7, 15, 26, 19,  5, 27, 15]])

**8. Matrix transposition**

Perform the matrix transposition of the matrix in question 7 and print out to the screen.

In [0]:
e = np.random.randint(0,30,size=(7, 15))
e.transpose()

array([[17, 25,  3, 25, 19, 10, 15],
       [23, 11, 10, 18, 16, 22, 21],
       [19,  8, 13,  3,  8,  8, 15],
       [10,  1, 20, 29, 10,  6,  3],
       [26, 26,  7, 11, 15, 14, 15],
       [ 6, 29, 18, 20, 25, 27, 12],
       [15, 24,  8, 16,  4, 29,  7],
       [26,  5,  6,  7, 11,  4, 25],
       [ 2,  4, 16, 23, 12, 24,  2],
       [ 2, 16, 23,  8, 15, 26, 25],
       [18, 10,  1, 13, 20, 14, 12],
       [18, 23, 16, 29,  1, 14, 28],
       [15, 20, 16, 13, 24, 25, 16],
       [13, 22, 10, 20, 23, 26,  4],
       [29, 21,  3, 14,  7, 10,  6]])

**9. Matrix addition**



1.   Automatically create 2 integer matrices whicch have values in the range of [-10, 30]
2.   Print them to the screen
3.   Perform matrix addition of the above 2 matrices and print the result to the screen. 



In [0]:
#Your code here